# Generated by Django 5.1.7 on 2025-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='esi_hi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='loan_recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
